import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Freedom Fighter DB Bank</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h2 className='text-9xl font-bold'>This is Homepage</h2>
      </div>
    </div>
  )
}
